// Données du catalogue de formation FORM RH, 17 thématiques.
// Source : PDF catalogue actuel (extrait dans le brief de refonte), sous-modules
// "nettoyage de jantes auto / salon de coiffure / salon de thé-chocolaterie" retirés
// de la thématique 17 à la demande de Rémi (à reconfirmer avec Céline plus tard).
module.exports = [
  {
    num: 1,
    icon: "target",
    slug: "strategie-entreprise-indicateurs",
    title: "Stratégie d'entreprise et indicateurs",
    accroche: "Poser une vision claire pour votre entreprise, et les indicateurs pour la piloter dans la durée.",
    keyword: "formation stratégie d'entreprise RH",
    modules: [
      "Mise en place d'une stratégie d'entreprise",
      "Trouver sa marque employeur",
      "Fonder son organigramme",
      "Construire sa cartographie des métiers",
      "Réaliser son diagnostic interne/externe",
      "Appliquer une conduite de changement",
      "Piloter par les tableaux de bord RH",
      "Choisir la structure d'entreprise qui vous ressemble",
      "Définir votre Business Model",
    ],
  },
  {
    num: 2,
    icon: "leaf",
    slug: "rse",
    title: "RSE (responsabilité sociale et environnementale)",
    accroche: "Faire de la RSE un levier de performance et d'attractivité, pas une contrainte administrative de plus.",
    keyword: "formation RSE entreprise",
    modules: [
      "Leadership durable",
      "Outils et méthodes pour une démarche RSE réussie",
      "Devenir une perma-entreprise",
      "Mettre en place le E dans la BDESE",
    ],
  },
  {
    num: 3,
    icon: "user-plus",
    slug: "recrutement-integration",
    title: "Recrutement et intégration",
    accroche: "Recruter juste, et donner à chaque nouvel arrivant toutes les chances de réussir et de rester.",
    keyword: "formation recrutement PME",
    modules: [
      "Créer son plan de recrutement",
      "Partenaires de recrutement",
      "Gérer un entretien",
      "Mises en situation",
      "Aides au recrutement",
      "Intégration réussie et fidélisation",
      "Recruter sans discriminer",
      "Cadre légal du recrutement",
      "Recruter la meilleure équipe",
    ],
  },
  {
    num: 4,
    icon: "folder",
    slug: "administration-rh",
    title: "Administration RH",
    accroche: "Maîtriser le quotidien administratif RH, sans y laisser tout votre temps de dirigeant.",
    keyword: "formation administration RH TPE PME",
    modules: [
      "Demandes des salariés (congés payés…)",
      "Procédures HS/HC/RCR/RTT",
      "L'essentiel de la gestion RH",
      "Vie administrative en entreprise",
      "Politique de rémunération",
      "Comprendre la réglementation",
    ],
  },
  {
    num: 5,
    icon: "heart-pulse",
    slug: "sante-travail",
    title: "Santé au travail",
    accroche: "Prévenir avant de subir : risques psycho-sociaux, climat social et qualité de vie au travail.",
    keyword: "formation santé au travail QVT",
    modules: [
      "Risques psycho-sociaux",
      "Harcèlement moral et sexuel",
      "DUERP",
      "Santé mentale au travail",
      "Qualité de vie au travail",
      "Gestion des conflits",
    ],
  },
  {
    num: 6,
    icon: "graduation-cap",
    slug: "gestion-formation",
    title: "Formation",
    accroche: "Faire de la formation un investissement piloté, pas une obligation légale gérée dans l'urgence.",
    keyword: "formation Qualiopi OPCO PME",
    modules: [
      "Actualité du droit de la formation",
      "Points-clés de la gestion de la formation",
      "Gérer la formation en TPE-PME",
      "Plan de développement des compétences",
      "Accompagnement au bilan de compétences",
      "Relations OPCO/FAF",
      "Aides au financement",
      "Salarié formé, salarié heureux",
      "Créer des supports pertinents",
      "Certification Qualiopi",
      "Méthodes pédagogiques innovantes",
    ],
  },
  {
    num: 7,
    icon: "timeline",
    slug: "gestion-carrieres-retraite",
    title: "Gestion des carrières jusqu'à la retraite",
    accroche: "Accompagner chaque étape du parcours professionnel, de l'entretien annuel au départ à la retraite.",
    keyword: "formation gestion des carrières RH",
    modules: [
      "Entretien professionnel",
      "Entretiens d'évaluation",
      "GEPP",
      "Mobilité interne",
      "Organigramme prévisionnel et fiche de poste",
      "Entretien des 6 ans",
      "Entretien de fin de carrière",
      "Accompagner vers la retraite",
      "Aligner objectifs personnels et professionnels",
    ],
  },
  {
    num: 8,
    icon: "scale",
    slug: "juridique-irp",
    title: "Juridique et IRP",
    accroche: "Sécuriser vos décisions RH sur des bases juridiques solides, au quotidien comme face aux IRP.",
    keyword: "formation droit social IRP CSE",
    modules: [
      "Pratique du droit social",
      "Droit du travail pour la fonction RH",
      "Droit du travail pour les managers",
      "Contrats CDI/CDD/Intérim",
      "Rupture du contrat",
      "Obligations légales",
      "Réunions CSE",
      "Initiation aux IRP / mise en place du CSE",
      "Élections professionnelles",
    ],
  },
  {
    num: 9,
    icon: "chat-bubbles",
    slug: "communication-interne-climat-social",
    title: "Communication interne et climat social",
    accroche: "Mieux communiquer en interne pour désamorcer les tensions avant qu'elles n'éclatent.",
    keyword: "formation communication interne entreprise",
    modules: [
      "Fondamentaux de la communication professionnelle",
      "Optimiser sa communication",
      "Communiquer avec sa hiérarchie",
      "Prise de parole en public",
      "Présentation efficace",
      "Prévention des conflits",
    ],
  },
  {
    num: 10,
    icon: "users-team",
    slug: "management",
    title: "Management",
    accroche: "Donner à vos managers les clés concrètes pour animer, motiver et faire grandir leurs équipes.",
    keyword: "formation management équipe PME",
    modules: [
      "Management des équipes",
      "Motiver et engager son équipe",
      "Influence managériale",
      "Manager en mode projet",
      "Management interculturel",
      "Relations non hiérarchiques constructives",
      "Leadership situationnel",
      "Organiser le travail d'une équipe",
      "Management intergénérationnel",
      "Animer une réunion",
      "Gérer son temps et ses priorités",
    ],
  },
  {
    num: 11,
    icon: "puzzle",
    slug: "diversite",
    title: "Diversité",
    accroche: "Construire un environnement de travail inclusif, conscient de ses biais et de ses angles morts.",
    keyword: "formation diversité inclusion entreprise",
    modules: [
      "Sensibilisation au handicap (salariés / managers)",
      "Diversité et inclusion",
      "Diversité culturelle",
      "Discrimination involontaire",
      "Religion au travail",
      "Diversité générationnelle",
      "Stéréotypes et préjugés",
    ],
  },
  {
    num: 12,
    icon: "smile",
    slug: "developpement-personnel",
    title: "Développement personnel",
    accroche: "Renforcer la confiance, l'équilibre et la posture de chacun, au bénéfice du collectif.",
    keyword: "formation développement personnel entreprise",
    modules: [
      "Confiance et estime de soi",
      "Charisme",
      "Gestion du stress et des émotions",
      "Lâcher prise",
      "Assertivité",
      "Équilibre vie pro/perso",
      "Connaître sa personnalité",
      "Résilience",
      "Confiance en soi et robotique",
      "Relations humaines et robotique",
      "Gestion du temps pro/perso",
    ],
  },
  {
    num: 13,
    icon: "sparkle",
    slug: "performance-par-le-plaisir",
    title: "Performance par le plaisir (PPLP)",
    accroche: "Une performance durable, construite sur le plaisir et l'engagement plutôt que sur la pression.",
    keyword: "formation performance plaisir management",
    modules: [
      "12 clés de réussite",
      "Patron libre et rentable",
      "Symbiocratie",
      "Environnement de travail stimulant",
      "Bien-être et performance durable",
      "Pratiques ludiques en management",
    ],
  },
  {
    num: 14,
    icon: "package",
    slug: "autres",
    title: "Autres",
    accroche: "Des formations transverses, pour les sujets qui ne rentrent dans aucune case.",
    keyword: "formation création entreprise marché public",
    modules: [
      "Créer son entreprise",
      "Répondre à un appel d'offres marché public",
      "Introduction au SIRH",
    ],
  },
  {
    num: 15,
    icon: "baby",
    slug: "parentalite",
    title: "Parentalité",
    accroche: "Accompagner la parentalité en entreprise, avec des outils concrets et une posture bienveillante.",
    keyword: "formation parentalité entreprise",
    modules: [
      "Naître Enchantés : conduites d'entretien orientées solutions",
      "Préparation à la naissance et à la parentalité",
    ],
  },
  {
    num: 16,
    icon: "cpu",
    slug: "intelligence-artificielle",
    title: "Intelligence artificielle",
    accroche: "Comprendre et utiliser l'intelligence artificielle concrètement, sans jargon technique inutile.",
    keyword: "formation intelligence artificielle PME",
    modules: [
      "Les bases de l'IA",
      "IA pour les cabinets comptables",
    ],
  },
  {
    num: 17,
    icon: "share",
    slug: "reseaux-sociaux",
    title: "Les réseaux sociaux",
    accroche: "Utiliser les réseaux sociaux et le digital pour développer et fidéliser sa clientèle, avec méthode.",
    keyword: "formation réseaux sociaux TPE",
    modules: [
      "Réseaux sociaux pour acquérir/fidéliser",
      "Campagnes emailing/SMS",
      "Stratégie digitale (activité événementielle/décoration)",
      "Communiquer sur ses réseaux",
    ],
  },
];
